export const actionTypes = {
	SELECT_ASSET: "SELECT_ASSET",

	CLICK_TIMELINE: "CLICK_TIMELINE",

	DESELECT_ASSET: "DESELECT_ASSET",

	FIT_TIMELINE_TO_FRAME: "FIT_TIMELINE_TO_FRAME",
	
	REMOVE_ASSET_FROM_PARENT: "REMOVE_ASSET_FROM_PARENT",

	DROP_ASSET: "DROP_ASSET",

	CALC_INSERT_POSITION: "CALC_INSERT_POSITION"
};

export const dndTypes = {
	ASSET: "ASSET",
	TIMELINE_ASSET: "TIMELINE_ASSET"
};
