export const SELECT_ASSET = "SELECT_ASSET";

export const CLICK_TIMELINE = "CLICK_TIMELINE";

export const DESELECT_ASSET = "DESELECT_ASSET";

export const FIT_TIMELINE_TO_FRAME = "FIT_TIMELINE_TO_FRAME";
